version: "3"
services:
  redis:
    image: redis

  app1:
    build: .
    environment:
      - REDIS_URL=redis://redis
    depends_on:
      - redis

  app2:
    build: .
    environment:
      - REDIS_URL=redis://redis
    depends_on:
      - redis

  nginx:
    image: nginx
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
